// SPDX-License-Identifier: MIT
// Copyright (c) 2024 nihui (https://github.com/nihui)
// Copyright (c) 2024 kernelbin (https://github.com/kernelbin)
//
// ruapu --- detect cpu isa features with single-file

#include <stdio.h>

#define RUAPU_IMPLEMENTATION
#include "ruapu.h"

int main()
{
    ruapu_init();

#define PRINT_ISA_SUPPORT(isa) printf("%s = %d\n", #isa, ruapu_supports(#isa));

#if defined(__i386__) || defined(__x86_64__) || defined(_M_IX86) || defined(_M_X64)
    PRINT_ISA_SUPPORT(mmx)
    PRINT_ISA_SUPPORT(sse)
    PRINT_ISA_SUPPORT(sse2)
    PRINT_ISA_SUPPORT(sse3)
    PRINT_ISA_SUPPORT(ssse3)
    PRINT_ISA_SUPPORT(sse41)
    PRINT_ISA_SUPPORT(sse42)
    PRINT_ISA_SUPPORT(sse4a)
    PRINT_ISA_SUPPORT(cmov)
#if defined(__x86_64__) || defined(_M_X64)
    PRINT_ISA_SUPPORT(lahflm)
#endif
    PRINT_ISA_SUPPORT(popcnt)
    PRINT_ISA_SUPPORT(pclmulqdq)
    PRINT_ISA_SUPPORT(movbe)
    PRINT_ISA_SUPPORT(clflush)
    PRINT_ISA_SUPPORT(clflushopt)
    PRINT_ISA_SUPPORT(clwb)
#if defined(__x86_64__) || defined(_M_X64)
    PRINT_ISA_SUPPORT(fsgsbase)
#endif
    PRINT_ISA_SUPPORT(bmi1)
    PRINT_ISA_SUPPORT(bmi2)
    PRINT_ISA_SUPPORT(adx)
    PRINT_ISA_SUPPORT(tbm)
    PRINT_ISA_SUPPORT(xop)
    PRINT_ISA_SUPPORT(avx)
    PRINT_ISA_SUPPORT(f16c)
    PRINT_ISA_SUPPORT(fma)
    PRINT_ISA_SUPPORT(fma4)
    PRINT_ISA_SUPPORT(avx2)
    PRINT_ISA_SUPPORT(avx512f)
    PRINT_ISA_SUPPORT(avx512bw)
    PRINT_ISA_SUPPORT(avx512cd)
    PRINT_ISA_SUPPORT(avx512dq)
    PRINT_ISA_SUPPORT(avx512vl)
    PRINT_ISA_SUPPORT(avx512pf)
    PRINT_ISA_SUPPORT(avx512er)
    PRINT_ISA_SUPPORT(avx512ifma)
    PRINT_ISA_SUPPORT(avx512vbmi)
    PRINT_ISA_SUPPORT(avx512vbmi2)
    PRINT_ISA_SUPPORT(avx512vnni)
    PRINT_ISA_SUPPORT(avx512bitalg)
    PRINT_ISA_SUPPORT(avx512vpopcntdq)
    PRINT_ISA_SUPPORT(avx512vp2intersect)
    PRINT_ISA_SUPPORT(avx512bf16)
    PRINT_ISA_SUPPORT(avx512fp16)
    PRINT_ISA_SUPPORT(avx5124fmaps)
    PRINT_ISA_SUPPORT(avx5124vnniw)
    PRINT_ISA_SUPPORT(avx512bmm)
    PRINT_ISA_SUPPORT(avxvnni)
    PRINT_ISA_SUPPORT(avxvnniint8)
    PRINT_ISA_SUPPORT(avxvnniint16)
    PRINT_ISA_SUPPORT(avxifma)
    PRINT_ISA_SUPPORT(avxneconvert)
    PRINT_ISA_SUPPORT(vpclmulqdq)
    PRINT_ISA_SUPPORT(amxfp16)
    PRINT_ISA_SUPPORT(amxbf16)
    PRINT_ISA_SUPPORT(amxint8)
    PRINT_ISA_SUPPORT(amxtile)
    PRINT_ISA_SUPPORT(gfni)
    PRINT_ISA_SUPPORT(aesni)
    PRINT_ISA_SUPPORT(vaes)
    PRINT_ISA_SUPPORT(sha1)
    PRINT_ISA_SUPPORT(sha256)
    PRINT_ISA_SUPPORT(sha512)
    PRINT_ISA_SUPPORT(sm3)
    PRINT_ISA_SUPPORT(sm4)
    PRINT_ISA_SUPPORT(pku)
    PRINT_ISA_SUPPORT(rdpid)
    PRINT_ISA_SUPPORT(serialize)
#if defined(__x86_64__) || defined(_M_X64)
    PRINT_ISA_SUPPORT(movrs)
#endif
    PRINT_ISA_SUPPORT(rdpru)
    PRINT_ISA_SUPPORT(rdrand)
    PRINT_ISA_SUPPORT(rdseed)
    PRINT_ISA_SUPPORT(tsx)
#if defined(__x86_64__) || defined(_M_X64)
    PRINT_ISA_SUPPORT(apx)
#endif
#elif __aarch64__ || defined(_M_ARM64)
    PRINT_ISA_SUPPORT(neon)
    PRINT_ISA_SUPPORT(fp)
    PRINT_ISA_SUPPORT(fphp)
    PRINT_ISA_SUPPORT(vfpv4)
    PRINT_ISA_SUPPORT(lse)
    PRINT_ISA_SUPPORT(lrcpc)
    PRINT_ISA_SUPPORT(ilrcpc)
    PRINT_ISA_SUPPORT(lrcpc3)
    PRINT_ISA_SUPPORT(lse128)
    PRINT_ISA_SUPPORT(lsfe)
    PRINT_ISA_SUPPORT(cpuid)
    PRINT_ISA_SUPPORT(flagm)
    PRINT_ISA_SUPPORT(flagm2)
    PRINT_ISA_SUPPORT(rng)
    PRINT_ISA_SUPPORT(fpmr)
    PRINT_ISA_SUPPORT(gcs)
    PRINT_ISA_SUPPORT(poe)
    PRINT_ISA_SUPPORT(cssc)
    PRINT_ISA_SUPPORT(cmpbr)
    PRINT_ISA_SUPPORT(hbc)
    PRINT_ISA_SUPPORT(fprcvt)
    PRINT_ISA_SUPPORT(asimdrdm)
    PRINT_ISA_SUPPORT(asimdhp)
    PRINT_ISA_SUPPORT(asimddp)
    PRINT_ISA_SUPPORT(asimdfhm)
    PRINT_ISA_SUPPORT(bf16)
    PRINT_ISA_SUPPORT(i8mm)
    PRINT_ISA_SUPPORT(frint)
    PRINT_ISA_SUPPORT(jscvt)
    PRINT_ISA_SUPPORT(fcma)
    PRINT_ISA_SUPPORT(faminmax)
    PRINT_ISA_SUPPORT(lut)
    PRINT_ISA_SUPPORT(f8cvt)
    PRINT_ISA_SUPPORT(f8fma)
    PRINT_ISA_SUPPORT(f8dp4)
    PRINT_ISA_SUPPORT(f8dp2)
    PRINT_ISA_SUPPORT(f8mm8)
    PRINT_ISA_SUPPORT(f8mm4)
    PRINT_ISA_SUPPORT(f16mm)
    PRINT_ISA_SUPPORT(f16f32dot)
    PRINT_ISA_SUPPORT(f16f32mm)
    PRINT_ISA_SUPPORT(mops)
    PRINT_ISA_SUPPORT(mte)
    PRINT_ISA_SUPPORT(mte2)
    PRINT_ISA_SUPPORT(sve)
    PRINT_ISA_SUPPORT(sve2)
    PRINT_ISA_SUPPORT(sve2p1)
    PRINT_ISA_SUPPORT(sve2p2)
    PRINT_ISA_SUPPORT(sve2p3)
    PRINT_ISA_SUPPORT(svebf16)
    PRINT_ISA_SUPPORT(svei8mm)
    PRINT_ISA_SUPPORT(svef32mm)
    PRINT_ISA_SUPPORT(svef64mm)
    PRINT_ISA_SUPPORT(svef16mm)
    PRINT_ISA_SUPPORT(sveeltperm)
    PRINT_ISA_SUPPORT(sveaes2)
    PRINT_ISA_SUPPORT(svebfscale)
    PRINT_ISA_SUPPORT(sveb16b16)
    PRINT_ISA_SUPPORT(sveb16mm)
    PRINT_ISA_SUPPORT(svelut6)
    PRINT_ISA_SUPPORT(svepmull)
    PRINT_ISA_SUPPORT(svebitperm)
    PRINT_ISA_SUPPORT(sveaes)
    PRINT_ISA_SUPPORT(svesha3)
    PRINT_ISA_SUPPORT(svesm4)
    PRINT_ISA_SUPPORT(sme)
    PRINT_ISA_SUPPORT(smei16i64)
    PRINT_ISA_SUPPORT(smef64f64)
    PRINT_ISA_SUPPORT(smei8i32)
    PRINT_ISA_SUPPORT(smef16f32)
    PRINT_ISA_SUPPORT(smeb16f32)
    PRINT_ISA_SUPPORT(smef32f32)
    PRINT_ISA_SUPPORT(smefa64)
    PRINT_ISA_SUPPORT(sme2)
    PRINT_ISA_SUPPORT(sme2p1)
    PRINT_ISA_SUPPORT(sme2p2)
    PRINT_ISA_SUPPORT(sme2p3)
    PRINT_ISA_SUPPORT(smei16i32)
    PRINT_ISA_SUPPORT(smebi32i32)
    PRINT_ISA_SUPPORT(smeb16b16)
    PRINT_ISA_SUPPORT(smef16f16)
    PRINT_ISA_SUPPORT(smeaes)
    PRINT_ISA_SUPPORT(smesbitperm)
    PRINT_ISA_SUPPORT(smef8f16)
    PRINT_ISA_SUPPORT(smef8f32)
    PRINT_ISA_SUPPORT(smelut6)
    PRINT_ISA_SUPPORT(smelutv2)
    PRINT_ISA_SUPPORT(smesf8fma)
    PRINT_ISA_SUPPORT(smesf8dp2)
    PRINT_ISA_SUPPORT(smesf8dp4)
    PRINT_ISA_SUPPORT(smesfexpa)
    PRINT_ISA_SUPPORT(smesmop4)
    PRINT_ISA_SUPPORT(smestmop)
    PRINT_ISA_SUPPORT(pmull)
    PRINT_ISA_SUPPORT(crc32)
    PRINT_ISA_SUPPORT(aes)
    PRINT_ISA_SUPPORT(sha1)
    PRINT_ISA_SUPPORT(sha2)
    PRINT_ISA_SUPPORT(sha3)
    PRINT_ISA_SUPPORT(sha512)
    PRINT_ISA_SUPPORT(sm3)
    PRINT_ISA_SUPPORT(sm4)
    PRINT_ISA_SUPPORT(amx)
    PRINT_ISA_SUPPORT(paca)
    PRINT_ISA_SUPPORT(pacg)
#elif __arm__ || defined(_M_ARM)
    PRINT_ISA_SUPPORT(half)
    PRINT_ISA_SUPPORT(edsp)
    PRINT_ISA_SUPPORT(vfp)
    PRINT_ISA_SUPPORT(fphp)
    PRINT_ISA_SUPPORT(neon)
    PRINT_ISA_SUPPORT(vfpv4)
    PRINT_ISA_SUPPORT(idiv)
    PRINT_ISA_SUPPORT(asimdhp)
    PRINT_ISA_SUPPORT(asimddp)
    PRINT_ISA_SUPPORT(asimdfhm)
    PRINT_ISA_SUPPORT(asimdbf16)
    PRINT_ISA_SUPPORT(i8mm)
#if !__thumb__
    PRINT_ISA_SUPPORT(iwmmxt)
#endif
    PRINT_ISA_SUPPORT(aes)
    PRINT_ISA_SUPPORT(pmull)
    PRINT_ISA_SUPPORT(sha1)
    PRINT_ISA_SUPPORT(sha2)
    PRINT_ISA_SUPPORT(crc32)
#elif __mips__
    PRINT_ISA_SUPPORT(msa)
    PRINT_ISA_SUPPORT(mxu)
    PRINT_ISA_SUPPORT(mxu2)
    PRINT_ISA_SUPPORT(mxu3)
    PRINT_ISA_SUPPORT(mmi)
    PRINT_ISA_SUPPORT(sx)
    PRINT_ISA_SUPPORT(asx)
    PRINT_ISA_SUPPORT(msa2)
    PRINT_ISA_SUPPORT(crypto)

#elif __ppc__ || __powerpc__
    PRINT_ISA_SUPPORT(altivec)
    PRINT_ISA_SUPPORT(vsx)

#elif __s390x__
    PRINT_ISA_SUPPORT(zvector)

#elif __loongarch__
    PRINT_ISA_SUPPORT(lsx)
    PRINT_ISA_SUPPORT(lasx)

#elif __riscv
    PRINT_ISA_SUPPORT(i)
    PRINT_ISA_SUPPORT(m)
    PRINT_ISA_SUPPORT(a)
    PRINT_ISA_SUPPORT(f)
    PRINT_ISA_SUPPORT(d)
    PRINT_ISA_SUPPORT(c)
    PRINT_ISA_SUPPORT(p)
    PRINT_ISA_SUPPORT(v)
    PRINT_ISA_SUPPORT(zaamo)
    PRINT_ISA_SUPPORT(zabha)
    PRINT_ISA_SUPPORT(zacas)
    PRINT_ISA_SUPPORT(zalasr)
    PRINT_ISA_SUPPORT(zalrsc)
    PRINT_ISA_SUPPORT(zawrs)
    PRINT_ISA_SUPPORT(zba)
    PRINT_ISA_SUPPORT(zbb)
    PRINT_ISA_SUPPORT(zbc)
    PRINT_ISA_SUPPORT(zbkb)
    PRINT_ISA_SUPPORT(zbkc)
    PRINT_ISA_SUPPORT(zbkx)
    PRINT_ISA_SUPPORT(zbpbo)
    PRINT_ISA_SUPPORT(zbs)
    PRINT_ISA_SUPPORT(zca)
    PRINT_ISA_SUPPORT(zcb)
    PRINT_ISA_SUPPORT(zcd)
#if __riscv_xlen == 32
    PRINT_ISA_SUPPORT(zcf)
    PRINT_ISA_SUPPORT(zclsd)
#endif
    PRINT_ISA_SUPPORT(zcmop)
    PRINT_ISA_SUPPORT(zfa)
    PRINT_ISA_SUPPORT(zfbfmin)
    PRINT_ISA_SUPPORT(zfh)
    PRINT_ISA_SUPPORT(zfhmin)
    PRINT_ISA_SUPPORT(zicbom)
    PRINT_ISA_SUPPORT(zicbop)
    PRINT_ISA_SUPPORT(zicntr)
    PRINT_ISA_SUPPORT(zicond)
    PRINT_ISA_SUPPORT(zicsr)
    PRINT_ISA_SUPPORT(zifencei)
    PRINT_ISA_SUPPORT(zihintpause)
    PRINT_ISA_SUPPORT(zihpm)
#if __riscv_xlen == 32
    PRINT_ISA_SUPPORT(zilsd)
#endif
    PRINT_ISA_SUPPORT(zimop)
    PRINT_ISA_SUPPORT(zknd)
    PRINT_ISA_SUPPORT(zkne)
    PRINT_ISA_SUPPORT(zknh)
    PRINT_ISA_SUPPORT(zkr)
    PRINT_ISA_SUPPORT(zksed)
    PRINT_ISA_SUPPORT(zksh)
    PRINT_ISA_SUPPORT(zmmul)
    PRINT_ISA_SUPPORT(zpn)
    PRINT_ISA_SUPPORT(zpsfoperand)
    PRINT_ISA_SUPPORT(zvbb)
    PRINT_ISA_SUPPORT(zvbc)
    PRINT_ISA_SUPPORT(zve32f)
    PRINT_ISA_SUPPORT(zve32x)
    PRINT_ISA_SUPPORT(zve64d)
    PRINT_ISA_SUPPORT(zve64f)
    PRINT_ISA_SUPPORT(zve64x)
    PRINT_ISA_SUPPORT(zvfbfmin)
    PRINT_ISA_SUPPORT(zvfbfwma)
    PRINT_ISA_SUPPORT(zvfh)
    PRINT_ISA_SUPPORT(zvfhmin)
    PRINT_ISA_SUPPORT(zvkb)
    PRINT_ISA_SUPPORT(zvkg)
    PRINT_ISA_SUPPORT(zvkned)
    PRINT_ISA_SUPPORT(zvknha)
    PRINT_ISA_SUPPORT(zvknhb)
    PRINT_ISA_SUPPORT(zvksed)
    PRINT_ISA_SUPPORT(zvksh)
    PRINT_ISA_SUPPORT(zvl32b)
    PRINT_ISA_SUPPORT(zvl64b)
    PRINT_ISA_SUPPORT(zvl128b)
    PRINT_ISA_SUPPORT(zvl256b)
    PRINT_ISA_SUPPORT(zvl512b)
    PRINT_ISA_SUPPORT(zvl1024b)

    PRINT_ISA_SUPPORT(xsfvfnrclipxfqf)
    PRINT_ISA_SUPPORT(xsfvfwmaccqqq)
    PRINT_ISA_SUPPORT(xsfvqmaccdod)
    PRINT_ISA_SUPPORT(xsfvqmaccqoq)

    PRINT_ISA_SUPPORT(xsmtvfmadotf32)
    PRINT_ISA_SUPPORT(xsmtvfwmadotf16)
    PRINT_ISA_SUPPORT(xsmtvmadothpi4)
    PRINT_ISA_SUPPORT(xsmtvmadothpi8)
    PRINT_ISA_SUPPORT(xsmtvmadoti4)
    PRINT_ISA_SUPPORT(xsmtvmadoti8)
    PRINT_ISA_SUPPORT(xsmtvmadotni8)
    PRINT_ISA_SUPPORT(xsmtvnspack)
    PRINT_ISA_SUPPORT(xsmtvpack)

    PRINT_ISA_SUPPORT(xtheadba)
    PRINT_ISA_SUPPORT(xtheadbb)
    PRINT_ISA_SUPPORT(xtheadbs)
    PRINT_ISA_SUPPORT(xtheadcondmov)
    PRINT_ISA_SUPPORT(xtheadfmemidx)
    PRINT_ISA_SUPPORT(xtheadfmv)
    PRINT_ISA_SUPPORT(xtheadmac)
    PRINT_ISA_SUPPORT(xtheadmemidx)
    PRINT_ISA_SUPPORT(xtheadmempair)
    PRINT_ISA_SUPPORT(xtheadsync)
    PRINT_ISA_SUPPORT(xtheadvdot)
    PRINT_ISA_SUPPORT(xtheadvector)

#elif __openrisc__
    PRINT_ISA_SUPPORT(orbis32)
    PRINT_ISA_SUPPORT(orbis64)
    PRINT_ISA_SUPPORT(orfpx32)
    PRINT_ISA_SUPPORT(orfpx64)
    PRINT_ISA_SUPPORT(orvdx64)

#endif

    const char* const* supported = ruapu_rua();
    while (*supported)
    {
        printf("%s\n", *supported);
        supported++;
    }

    return 0;
}
